name: Deploy Cloud Run (test)

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
    types:
      - 'opened'
      - 'synchronize'
      - 'edited'
      - 'reopened'
  workflow_dispatch:

concurrency:
  group: my-cfapps-portal-deploy-test

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      http_service_name: ${{ steps.set_name.outputs.http_service_name }}
      event_service_name: ${{ steps.set_name.outputs.event_service_name }}
    steps:
      - name: Set service name
        id: set_name
        run: |
          echo "http_service_name=my-cfapps-portal-test" >> $GITHUB_OUTPUT
          echo "event_service_name=my-cfapps-portal-test-event" >> $GITHUB_OUTPUT

  deploy-http:
    needs: prepare
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Google Cloud auth
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'cloud-run-functions-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ needs.prepare.outputs.http_service_name }}
          region: ${{ secrets.GCP_REGION }}
          source: .
          flags: --memory=256Mi
          env_vars: |-
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            GCP_REGION=${{ secrets.GCP_REGION }}
            GITHUB_PAT=${{ secrets.GH_PAT }}
            GITHUB_OWNER=${{ secrets.GH_OWNER }}
            APP_ENV=test
          secrets: |-
            GCLOUD_SERVICE_ACCOUNT=GCLOUD_SERVICE_ACCOUNT:latest

  # deploy-event:
  #   needs: prepare
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: 'true'

  #     - name: Google Cloud auth
  #       id: auth
  #       uses: google-github-actions/auth@v3
  #       with:
  #         workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
  #         service_account: 'cloud-run-functions-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

  #     - name: Deploy to Cloud Run
  #       id: deploy
  #       uses: google-github-actions/deploy-cloudrun@v3
  #       with:
  #         service: ${{ needs.prepare.outputs.event_service_name }}
  #         region: ${{ secrets.GCP_REGION }}
  #         source: .
  #         flags: --memory=256Mi
  #         env_vars: |-
  #           GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
  #           GCP_REGION=${{ secrets.GCP_REGION }}
  #           GITHUB_PAT=${{ secrets.GH_PAT }}
  #           GITHUB_OWNER=${{ secrets.GH_OWNER }}
  #           APP_ENV=test
  #         secrets: |-
  #           GCLOUD_SERVICE_ACCOUNT=GCLOUD_SERVICE_ACCOUNT:latest

  comment:
    # needs: [prepare, deploy-http, deploy-event]
    needs: [prepare, deploy-http]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    permissions:
      pull-requests: write
      contents: read  # チェックアウトなど、他の操作に必要
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Add comment to PR
        run: |
          gh pr comment $PR_NUMBER --body "Deployed to url ${{ needs.deploy-http.outputs.url }} [skip ci]"
