name: Deploy Cloud Run (test)

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
    types:
      - 'opened'
      - 'synchronize'
      - 'edited'
      - 'reopened'
  workflow_dispatch:

concurrency:
  group: my-cfapps-portal-deploy-test

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      service_name: ${{ steps.set_name.outputs.service_name }}
    steps:
      - name: Set service name
        id: set_name
        run: |
          echo "service_name=my-cfapps-portal-test" >> $GITHUB_OUTPUT

  deploy:
    needs: prepare
    uses: yananob/cloud-functions-common/.github/workflows/deploy-cloud-functions.yaml@main
    with:
      function_name: ${{ needs.prepare.outputs.service_name }}
      service_account_name: 'cloud-run-functions-deployer'
      wip_pool_name: 'github-actions-pool'
      wip_provider_name: 'github-provider'
      runtime: nodejs22
      secrets_config: |-
        GH_PAT
        GH_OWNER
        GCLOUD_SERVICE_ACCOUNT
      deploy_http_trigger: true
      deploy_event_trigger: true
      http_max_instance_count: 1
      memory: '256M'
      environment_variables: |-
        GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
        GCP_REGION=${{ secrets.GCP_REGION }}
        GITHUB_PAT=${{ secrets.GH_PAT }}
        GITHUB_OWNER=${{ secrets.GH_OWNER }}
        APP_ENV=test
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}

  comment:
    needs: [prepare, deploy]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Add comment to PR
        run: |
          gh pr comment $PR_NUMBER --body "Deployed to url https://${{ secrets.GCP_REGION }}-${{ secrets.GCP_PROJECT_ID }}.cloudfunctions.net/${{ needs.prepare.outputs.service_name }} [skip ci]"
