name: Run test

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - test
  push:
    branches:
      - test
  workflow_dispatch:

concurrency:
  group: myapps-portal-run-test-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: .

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'true'

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: "24"
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: bash tests/run_tests.sh
